### ISSUE TITLE
sign up page

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#1]
**User Story**

As a visiting user, I would like to sign up so I could become a registered user and be able to book a table, edit my booking and view it. 

**Description**

The form needs to have the following fields:- 
- Name (String)
- Email (email)
- Password (password)
- re-type password (password)   -  _could have_
- username      _could have_

**Acceptance Criteria**
- A form should be displayed on the signup page. 
- If the user inputs all the information correctly the form should be submitted. 
- After submission, a toast message should be shown so the user knows, it has been submitted successfully. 
-  If the user inputs incorrect information, an error message should be displayed. 
- The user could not submit the form without completing all the fields. 

**Tasks**
- [x]  create a user interface for the signup page. 
- [x] Create a form inside the user interface on the signup page.
- [x]  Add input validation. 
- [x]   Create a submit button at the end form.
