### ISSUE TITLE
USER STORY: Header-Hero section 

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#12]
**User Story**

As a visiting and registered user, I would like to see a section hero in the homepage when I open the website so I would be able to see initial information about the restaurant such as a welcome message,  reservation button, and videos of the restaurant. 

**Acceptance Criteria** 

-  I can see an embedded video in the heading.
-  Videos of the restaurant change automatically. 
-  Next and previous option is a carousel design so that the user goes back and ford to see other videos of the restaurant. 
- The main or first carousel should have a welcome message and a button for reservation. 
- Other carousels should give a meaningful message to the user. 

**Tasks**

- [x]  Use bootstrap
- [x]  Create a carousel wrapper
- [x]  Add an embedded video into each carousel. 
- [x]  Add a welcome message in the first header or carousel.
- [x]  Add a reservation button in the first carousel video.

**Comment by MuzhdaN** [comment]
To do at the end

- [x]  check the responsive of the texts and buttons at the end
