### ISSUE TITLE
USER STORY: contact us section

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#13]
**USER STORY**
As a user, I would like to see a contact section so that I would be able to find the restaurant address and contact them if necessary. 

**Acceptance Criteria** 

-  Contact section on the homepage.
-  Map should be included.
-  Address and contact numbers of the restaurant should be included. 

**Tasks**

- [x]  Add a section on the homepage
- [x]  Create two columns (use bootstrap)
- [x]  Add map on left side
- [x]  Add address and contact info on the right side

**Comment by MuzhdaN** [comment]
Bug: not responsive in mobile devices
