### ISSUE TITLE
USER STORY: book a table

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#15]
**USER STORY**
As a user, I would like to book a table so that my table would be ready beforehand. 

**Description**
the form needs to have the following fields:

- First Name (String)
- Last Name (String)
- Email (email)
- Guests numbers (number)
- Date (date)
- Time (time)

**Acceptance Criteria** 

-  reservation should only be made by a logged-in user. 
- a form is displayed on the reservation page. 
-  If all the information in the form is correct it should be successfully submitted, and a success toast should be shown to the user.
-  if one or all of the information is incorrect an error should be displayed to the user. 
     
**Tasks**
- [x] create a form on the reservation page. 
- [x] create a modal on the reservation page.
- [x] add input validation in the form. 
- [x] create the view to take the form and input it in the database. (backend)
- [x]  add design to the page
