### ISSUE TITLE
create a reservation page

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#16]
**User Story**
As a user, I would like to check go to the reservation page so that I could book/reserve a table and check the opening days and hours of the restaurant. 

**Acceptance Criteria**

- heading for the page should be displayed with a bg-image.
- a separate page should be made for reservations. 
- business days should be displayed.
- a form should be displayed. 
- reservation page should be only given access to the logged-in users.

**Tasks**

- [x] Create a separate page for reservations.
- [x] create a form on this page.
- [ ] create an opinion hours section.  (Optional)
