### ISSUE TITLE
USER STORY: view bookings

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#19]
As a user I would like to see my bookings so that I could see my bookings details. 

**Acceptance Criteria** 

-  The user can view their booking
- The user can see two options to edit or cancel her booking
- The user can see her booking if she is logged in.

**Tasks**

- [x]  Create a separate HTML page to manage the bookings
- [x]  user should be able to see her updated bookings
- [x]  Create two buttons to edit and cancel the bookings
- [x]  extend the header and footer from the base.html 
- [x]  Add user authentication for the booking.

**Comment by MuzhdaN** [comment]
Issue: The logged-in user's data is not showing!!!!
