### ISSUE TITLE
Login page 

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#2]
**User Story**

As a registered user, I want to log in with my email and password so that the system can authenticate me and I can book a table or view and edit my bookings. 

**Description**

The form needs to have the following fields:-
- Email (email)
- Password (password)

**Acceptance Criteria** 

-  Given that I am a registered user and log out of my account. If I go to the login page and enter with an incorrect email and correct password and click the login button, then it should show an error message that says that the email or password is incorrect. 
-  Given that I am a registered user and log out of my account. If I go to the login page and enter the correct email and incorrect password and click the login button, then it should show an error message that says that the email or password is incorrect. 

**Tasks**
- [x]  Create a user interface for the login page
- [x]  Create a form for the login page. 
- [x]  Create a login button at the end of the form. 
- [x]  Add input validation.
