### ISSUE TITLE
USER STORY: Cancel booking

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#20]
**USER STORY**
As a user, I would like to cancel my booking if I change my mind to go to the restaurant. 

**Description**

- On the cancel confirmation page, the user should be asked again if they want to cancel the booking
          - two options should be given to the user:
         -  Yes (delete the booking from the booking list)
         -  No (return back to booking list)

**Acceptance Criteria** 

- The user should be able to delete her booking. 
- The user should be given a confirmation message in case she changes her mind or has pressed the button by mistake.

**Tasks**

- [x] Create a delete button on the booking list page
- [x]  Create a delete booking HTML page
- [x]  Connect HTML with the cancel button
- [x]  create a delete function in the views of the reservation app (Django)
- [x]  add delete booking URL in URLs.py of the reservation app

**Comment by MuzhdaN** [comment]
Bug: 'No' option deletes the booking 
solved

**Comment by MuzhdaN** [comment]
bug: it is not working, a 404 error will be displayed
the error was the same as https://github.com/MuzhdaN/FEAST/issues/21 and was solved accordingly.
