### ISSUE TITLE
USER STORY: Edit booking

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#21]
**USER STORY**
As a user, I would like to edit my booking so that if I wanted to change my reservation info. 

**Description**
A toast or success message isn't a must but the developer could add it if there was enough time. 
As the user would be directed to the bookings page, she will be able to see that her booking-info has been updated 

**Acceptance Criteria**

-  A edit button should be displayed on the booking list page.
- The edit option should direct the user to another page so that the user could edit or update her booking. 
-  After submitting the edit form the user should be directed to the bookings page. 

**Tasks**

- [x]  Create or extend a form to show the info about the booking in a separate HTML page by the name of 'edit_booking.html'
- [x]  After the user submits the form, it should redirect her to the bookings page.
- [x]  Add a success message (toast) so the user knows that the form has been updated. (Could have)
- [x]  create a  function in the views of the reservation app (Django) for edit booking
- [x]  add its URL in urls.py of the reservation app

**Comment by MuzhdaN** [comment]
bug: its not working,  404 error will be displayed

**Comment by MuzhdaN** [comment]
The following error was displayed while the user wanted to edit her booking. 
Solved: in the main URLs the path url should be left blank. 

Path when the error was occuring: `path('reservation/', include('reservation.urls', namespace='reservation')),`

After using an empty string, it didn't give any error: 
`path('', include('reservation.urls', namespace='reservation')),`

![Image](https://user-images.githubusercontent.com/79607397/211165143-28432c28-e81d-440e-95a6-981fa97e683c.PNG)
