### ISSUE TITLE
USER STORY: Home page - About us section

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#4]
As a visiting user and registered user, I want to know more about the restaurant.

**Acceptance Criteria**

-  Create a heading for this section as "About Us". 
- Create an about me section or model on the home page. 
-  Write a short history of the website. 
-  Show some of the restaurant pictures behind about us content. 

**Tasks**

- [x]  Create an about us model like a section or a model on the home page.
- [x]  Create a heading for this section.
- [x]  Create a model so you could put the content (history of the restaurant) inside it. 
- [x]  Create a collage (where two or three images of the restaurant are shown) next to the content.
