### ISSUE TITLE
USER STORY: Header- Navbar 

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#5]
As a visiting and registered user, I would like to see the navigation bar at the top of the homepage, so that I can see the logo of the website and easily navigate to the other pages. 

**Acceptance Criteria** 

-  When I arrive at the home page, I will be able to see the logo. 
-  I would be able to see the hamburger navbar.
-  When I click the hamburger navigation, the sidebar navbar opens. 
- I would like to have the login and register button at the right corner of the navbar. 
-  If I click outside of the sidebar nav, it closes. 

**Tasks**

- [x]  Use bootstrap
- [x]  Create a logo at the top center of the header. 
- [x]  Create hamburger navigation in the top left side of the header. 
- [x]  Create a sidebar nav.
- [x]  Create a close button at the top right side of the sidebar
- [x]  sidebar should be opened from the left side.

**Comment by MuzhdaN** [comment]
**Bug**: the text in the sticky navbar can't be seen when the page is scrolled. 
**Solution:** The sticky header content bg-color and color should be changed.

**Comment by MuzhdaN** [comment]
Bug: off-canvas contents not showing after rendering it to the Django template
Solution: CSS link path was not correct in the base.html
