### ISSUE TITLE
USER STORY:  Home page - team section

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#7]
**USER STORY**
As a visiting and registered user, I would like to know about the main chefs of the restaurant so I would know who has cooked the delicious foods and also know about their qualifications. 

**Acceptance Criteria**

-  Check the main chefs. 
-  Check chefs' qualifications. 
-  Check chefs' positions.

**Tasks**

- [x]  Create a Team section on the home page.
- [x]  Create a heading for it. 
- [x]  Create the main model and three sub-model inside it. 
- [x]  Inside the sub-model, display the chef's image, name, and position.
- [x] Add social media icons.
- [x]  Add external social media links.
