### ISSUE TITLE
USER STORY:  Home page - customer reviews 

### ISSUE THREAD

**Issue by MuzhdaN** [MuzhdaN/FEAST#8]
**USER STORY**

As a visiting and registered user, I would like to see what other customer's says about the restaurant so I would be able to know if this is a good restaurant or not. 

**Acceptance Criteria**

-  I can see reviews of other people. 
-  The user could see the image of the reviewer so the review could be authentic. 

**Tasks**

- [x]  User Bootstrap modal
- [x]  Create a customer reviews section on the home page. 
- [x]  Create a model and inside it add the user's image, name, and review. 
- [x]  Display customer reviews one at a time. 
- [x]  Add buttons on the left and right to change the reviews.
